//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.FormService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormData", Namespace="http://schemas.datacontract.org/2004/07/iPAS_UserService_DAL.Model")]
    [System.SerializableAttribute()]
    public partial class FormData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dob {
            get {
                return this.DobField;
            }
            set {
                if ((object.ReferenceEquals(this.DobField, value) != true)) {
                    this.DobField = value;
                    this.RaisePropertyChanged("Dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meal {
            get {
                return this.MealField;
            }
            set {
                if ((object.ReferenceEquals(this.MealField, value) != true)) {
                    this.MealField = value;
                    this.RaisePropertyChanged("Meal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FormService.IFormService")]
    public interface IFormService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormService/Welcome", ReplyAction="http://tempuri.org/IFormService/WelcomeResponse")]
        string Welcome(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormService/Welcome", ReplyAction="http://tempuri.org/IFormService/WelcomeResponse")]
        System.Threading.Tasks.Task<string> WelcomeAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormService/RegistrationFormData", ReplyAction="http://tempuri.org/IFormService/RegistrationFormDataResponse")]
        Registration.FormService.FormData RegistrationFormData(Registration.FormService.FormData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormService/RegistrationFormData", ReplyAction="http://tempuri.org/IFormService/RegistrationFormDataResponse")]
        System.Threading.Tasks.Task<Registration.FormService.FormData> RegistrationFormDataAsync(Registration.FormService.FormData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormService/CalculateDays", ReplyAction="http://tempuri.org/IFormService/CalculateDaysResponse")]
        int CalculateDays(int day, int Month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormService/CalculateDays", ReplyAction="http://tempuri.org/IFormService/CalculateDaysResponse")]
        System.Threading.Tasks.Task<int> CalculateDaysAsync(int day, int Month, int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFormServiceChannel : Registration.FormService.IFormService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormServiceClient : System.ServiceModel.ClientBase<Registration.FormService.IFormService>, Registration.FormService.IFormService {
        
        public FormServiceClient() {
        }
        
        public FormServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Welcome(string name) {
            return base.Channel.Welcome(name);
        }
        
        public System.Threading.Tasks.Task<string> WelcomeAsync(string name) {
            return base.Channel.WelcomeAsync(name);
        }
        
        public Registration.FormService.FormData RegistrationFormData(Registration.FormService.FormData data) {
            return base.Channel.RegistrationFormData(data);
        }
        
        public System.Threading.Tasks.Task<Registration.FormService.FormData> RegistrationFormDataAsync(Registration.FormService.FormData data) {
            return base.Channel.RegistrationFormDataAsync(data);
        }
        
        public int CalculateDays(int day, int Month, int year) {
            return base.Channel.CalculateDays(day, Month, year);
        }
        
        public System.Threading.Tasks.Task<int> CalculateDaysAsync(int day, int Month, int year) {
            return base.Channel.CalculateDaysAsync(day, Month, year);
        }
    }
}
